### ISSUE TITLE
这个项目是和xSocks一起使用的吗？

### ISSUE THREAD

**Issue by somebodyZw** [dosgo/xSocks-android#1]
[请问这个项目是和xSocks是一起使用的吗？[xSocks](https://github.com/dosgo/xSocks/tree/master/cli)作为服务器，这个项目作为安卓客户端吗？]

**Comment by dosgo** [comment]
对的，安卓是这样，pc不用这个

**Comment by dosgo** [comment]
pc的话直接用xsocks的cli/client.go，然后浏览器设置代理地址就好了。。

**Comment by somebodyZw** [comment]
收到，谢谢，方便的话可以加个QQ学习下吗

**Comment by somebodyZw** [comment]
767586571
