### ISSUE TITLE
Why it not working without

### ISSUE THREAD

**Issue by evgenybozhko2** [dosgo/xSocks-android#2]
Why is it not working without calling `addAllowedApplication(packageName)` bypassing self method ? So with call this I can't have in VPN client app VPN access network. Or the whole app tunnel not working without calling it. `addAllowedApplication(packageName)`

How to solve that? And have connection to whole system and self app ?

**Comment by dosgo** [comment]
Normal, otherwise the data packet will be in an infinite loop. The data of this application needs to be sent to the gateway normally. If not, you can only call the protect method to protect the connected socket。

**Comment by evgenybozhko2** [comment]
And than I can access to vpn via com.my.app and com.google.chrome for example ?

**Comment by dosgo** [comment]
？？？？

**Comment by dosgo** [comment]
You need to supplement the knowledge related to vpn. . .

**Comment by evgenybozhko2** [comment]
You right. But what I know now. That whole device haven't connection without `addDisallowedApplication` method call. And that means the main app which run VPnService never will get access to tunnel. How solve that ?

**Comment by dosgo** [comment]
You need to know that the main program is a client that provides vpn service, what tunnel do you need?

**Comment by evgenybozhko2** [comment]
After connect, google chrome works with remote server IP. But my app which run VpnService works with my local old IP. How to solve it ?

**Comment by dosgo** [comment]
Do you want to develop a vpn? VPN is far more complicated than an encrypted proxy. You need to complete the data exchange on the remote server. The Android client only needs to send the tun data to the remote, and the server needs to register each vpn client tun on the server. The device and the network segment and ip are set up to complete the data exchange. Of course, you can also use the tcp/ip protocol stack to complete the exchange remotely, but you may have to manually construct the ip package. .

**Comment by evgenybozhko2** [comment]
I'm develop vpn socks5 app. Just need to pass all device traffic during server. So you implementation works well for me. But it stops after I just comment one line 
```
//Bypass self
builder.addDisallowedApplication(packageName)
```
Code is written with Kotlin.
So with this line I can't pass my app data with retrofit during my connected proxy socks5 via VpnService. Does it possible to have connection all devices apps and my app as well ?
